plugins {
    id("conventions.kotlin")
    id("conventions.kotlin-static-analysis")
    id("conventions.integration-test")
    id("test-feature-app")
    `java-test-fixtures`
}

viaductFeatureApp {
    sourceSetName.set("integrationTest")
}

viaductPublishing {
    name.set("Tenant Runtime")
    description.set("The Viaduct tenant runtime.")
}

dependencies {
    implementation(libs.caffeine)
    implementation(libs.graphql.java)
    implementation(libs.guice)
    implementation(libs.javax.inject)
    implementation(libs.viaduct.tenant.api)

    implementation(libs.viaduct.engine.api)
    implementation(libs.viaduct.service.api)

    implementation(libs.viaduct.shared.graphql)
    implementation(libs.viaduct.shared.mapping)
    implementation(libs.viaduct.shared.apiannotations)
    implementation(libs.viaduct.shared.utils)
    implementation(libs.classgraph)
    implementation(libs.guava)
    implementation(libs.slf4j.api)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.core.jvm)
    implementation(libs.viaduct.shared.apiannotations)

    testFixturesImplementation(libs.viaduct.engine.api)
    testFixturesImplementation(testFixtures(libs.viaduct.service.api))
    testFixturesImplementation(libs.viaduct.service.runtime)
    testFixturesImplementation(libs.viaduct.service.wiring)
    testFixturesImplementation(libs.slf4j.api)
    testFixturesImplementation(libs.viaduct.engine.runtime)
    testFixturesImplementation(libs.viaduct.service.api)
    testFixturesImplementation(libs.viaduct.tenant.api)
    testFixturesImplementation(libs.viaduct.tenant.wiring)
    testFixturesImplementation(testFixtures(libs.viaduct.tenant.api))
    testFixturesImplementation(libs.graphql.java)
    testFixturesImplementation(libs.io.mockk.jvm)
    testFixturesImplementation(libs.kotlin.reflect)
    testFixturesImplementation(libs.kotlinx.coroutines.core)
    testFixturesImplementation(libs.kotlinx.coroutines.jdk8)
    testFixturesImplementation(libs.kotlinx.coroutines.test)
    testImplementation(testFixtures(libs.viaduct.engine.api))
    testImplementation(testFixtures(libs.viaduct.service.api))
    testImplementation(testFixtures(libs.viaduct.shared.graphql))
    testImplementation(testFixtures(libs.viaduct.tenant.api))
    testImplementation(libs.viaduct.engine.runtime)
    testImplementation(libs.viaduct.service.runtime)
    testImplementation(libs.viaduct.shared.arbitrary)
    testImplementation(libs.io.mockk.dsl)
    testImplementation(libs.io.mockk.jvm)
    testImplementation(libs.jackson.core)
    testImplementation(libs.jackson.databind)
    testImplementation(libs.jackson.module)
    testImplementation(libs.kotest.property.jvm)
    testImplementation(libs.kotlinx.coroutines.jdk8)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.strikt.core)
    testImplementation(libs.micrometer.core)

    /** Codegen classpath for test-feature-app worker isolation **/
    viaductCodegenClasspath(libs.viaduct.tenant.codegen)

    /** Integration test dependencies **/
    integrationTestImplementation(testFixtures(libs.viaduct.engine.api))
    integrationTestImplementation(testFixtures(libs.viaduct.service.api))
    integrationTestImplementation(testFixtures(libs.viaduct.shared.graphql))
    integrationTestImplementation(testFixtures(libs.viaduct.tenant.api))
    integrationTestImplementation(libs.viaduct.engine.runtime)
    integrationTestImplementation(libs.viaduct.engine.wiring)
    integrationTestImplementation(libs.viaduct.tenant.wiring)
    integrationTestImplementation(libs.viaduct.service.runtime)
    integrationTestImplementation(libs.viaduct.shared.arbitrary)
    integrationTestImplementation(libs.guice)
    integrationTestImplementation(libs.io.mockk.dsl)
    integrationTestImplementation(libs.io.mockk.jvm)
    integrationTestImplementation(libs.jackson.core)
    integrationTestImplementation(libs.jackson.databind)
    integrationTestImplementation(libs.jackson.module)
    integrationTestImplementation(libs.kotest.property.jvm)
    integrationTestImplementation(libs.kotlinx.coroutines.jdk8)
    integrationTestImplementation(libs.kotlinx.coroutines.test)
    integrationTestImplementation(libs.assertj.core)
    integrationTestImplementation(libs.strikt.core)
    integrationTestImplementation(libs.micrometer.core)
    integrationTestImplementation(libs.slf4j.api)
}
