package viaduct.java.runtime.bootstrap;

import java.util.Set;
import viaduct.java.api.types.Arguments;
import viaduct.java.api.types.GRT;

/**
 * Interface for discovering resolver classes in Java tenant packages.
 *
 * <p>This is the Java equivalent of Kotlin's {@code TenantResolverClassFinder}, using {@link Class}
 * instead of {@code KClass} to avoid Kotlin-specific types in the Java API.
 *
 * <p>Implementations scan the classpath to find:
 *
 * <ul>
 *   <li>Resolver base classes annotated with {@code @ResolverFor}
 *   <li>Resolver implementations annotated with {@code @Resolver}
 *   <li>Generated GRT (GraphQL Representational Type) classes
 *   <li>Generated Arguments classes
 * </ul>
 *
 * <h2>Example Usage</h2>
 *
 * <pre>{@code
 * JavaResolverClassFinder finder = new DefaultJavaResolverClassFinder(
 *     "com.mycompany.resolvers",
 *     "com.mycompany.grts"
 * );
 *
 * // Find all @ResolverFor annotated base classes
 * Set<Class<?>> baseClasses = finder.resolverClassesInPackage();
 *
 * // Find implementations that extend a specific base class
 * Set<Class<? extends UserProfilePictureBase>> impls =
 *     finder.getSubTypesOf(UserProfilePictureBase.class);
 * }</pre>
 */
public interface JavaResolverClassFinder {

  /**
   * Discovers all {@code @ResolverFor} annotated classes in the configured package.
   *
   * <p>These are typically abstract base classes generated by codegen that define the resolver
   * contract for a specific GraphQL field.
   *
   * @return set of classes annotated with {@code @ResolverFor}
   */
  Set<Class<?>> resolverClassesInPackage();

  /**
   * Discovers all {@code @NodeResolverFor} annotated classes in the configured package.
   *
   * <p>These are base classes for Node resolvers that handle the {@code node(id: ID!)} query.
   *
   * @return set of classes annotated with {@code @NodeResolverFor}
   */
  Set<Class<?>> nodeResolverForClassesInPackage();

  /**
   * Finds all subclasses and implementors of the specified class in the configured package.
   *
   * <p>Used to find concrete resolver implementations that extend generated base classes.
   *
   * @param <T> the base type
   * @param type the base class or interface to find subtypes of
   * @return set of classes that extend or implement the specified type
   */
  <T> Set<Class<? extends T>> getSubTypesOf(Class<T> type);

  /**
   * Loads a generated GRT class by its GraphQL type name.
   *
   * <p>GRT (GraphQL Representational Type) classes are generated for each GraphQL object type and
   * represent the type-safe Java representation of that type.
   *
   * @param typeName the GraphQL type name (e.g., "User", "Product")
   * @return the corresponding generated GRT class
   * @throws ClassNotFoundException if no matching class is found
   */
  Class<? extends GRT> grtClassForName(String typeName) throws ClassNotFoundException;

  /**
   * Loads a generated Arguments class by its class name.
   *
   * <p>Arguments classes are generated for fields that have arguments, providing type-safe access
   * to those argument values.
   *
   * @param className the generated argument class name (e.g., "User_name_Arguments")
   * @return the corresponding generated Arguments class
   * @throws ClassNotFoundException if no matching class is found
   */
  Class<? extends Arguments> argumentClassForName(String className) throws ClassNotFoundException;
}
